version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - sdfbs-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - sdfbs-net

  fluentd:
    image: fluent/fluentd:v1.14-1
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./cloud/efk/fluent.conf:/fluentd/etc/fluent.conf:ro
    ports:
      - 24224:24224
      - 24224:24224/udp
    networks:
      - sdfbs-net

volumes:
  esdata:

networks:
  sdfbs-net:
    external: true
